name: Prevent CODEOWNERS Modification

on:
  pull_request:
    paths:
      - '.github/CODEOWNERS'

jobs:
  block-modification:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if CODEOWNERS is modified
        run: |
          echo "❌ CODEOWNERS file cannot be modified in this PR."
          exit 1
