name: Prevent Auto Edit of CODEOWNERS

on:
  pull_request:
    branches:
      - development
      - quality
      - main
      - hotfix

jobs:
  detect-codeowners-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for CODEOWNERS changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

          if git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep -q "^.github/CODEOWNERS$"; then
            echo "❌ CODEOWNERS file was modified. This should be resolved manually in GitHub UI."
            exit 1
          else
            echo "✅ CODEOWNERS untouched. Proceed with PR."
          fi

