name: Enforce Original CODEOWNERS from Target Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - development
      - quality
      - main
      - hotfix

  push:
    branches:
      - development
      - quality
      - main
      - hotfix

jobs:
  restore-original-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

      - name: Get target and head branch
        id: vars
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
            echo "HEAD_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
            echo "HEAD_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Restore CODEOWNERS from target branch HEAD
        run: |
          echo "🔁 Restoring CODEOWNERS from base branch: $TARGET_BRANCH"

          git fetch origin "$TARGET_BRANCH"
          git restore --source=origin/"$TARGET_BRANCH" --staged --worktree .github/CODEOWNERS

          echo "✅ CODEOWNERS reset to match $TARGET_BRANCH"

      - name: Commit and push restored CODEOWNERS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/CODEOWNERS
          git commit -m "ci: restore CODEOWNERS from $TARGET_BRANCH" || echo "ℹ️ No changes to commit"
          git push origin HEAD:$HEAD_BRANCH || echo "ℹ️ Push skipped"
