name: Enforce Target Branch CODEOWNERS

on:
  pull_request:

jobs:
  preserve-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch target branch (base)
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Overwrite CODEOWNERS with target branch version
        run: |
          git checkout origin/${{ github.event.pull_request.base.ref }} -- .github/CODEOWNERS
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (
            git commit -am "ci: preserve CODEOWNERS from ${{ github.event.pull_request.base.ref }}"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          )
