name: Sync CODEOWNERS Template

on:
  push:
    branches:
      - development
      - quality
      - main
      - hotfix

  pull_request:
    branches:
      - development
      - quality
      - main
      - hotfix

jobs:
  sync-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine branch and copy template
        run: |
          BRANCH="${{ github.event.pull_request.base.ref || github.ref_name }}"
          echo "🧠 Detected branch: $BRANCH"

          TEMPLATE_FILE=".github/templates/CODEOWNERS.$BRANCH"
          TARGET_FILE=".github/CODEOWNERS"

          if [ ! -f "$TEMPLATE_FILE" ]; then
            echo "⚠️ No template found for $BRANCH. Skipping..."
            exit 0
          fi

          cp "$TEMPLATE_FILE" "$TARGET_FILE"

          if ! git diff --quiet; then
            echo "✅ CODEOWNERS updated from template. Committing..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add "$TARGET_FILE"
            git commit -m "ci: synced CODEOWNERS from $TEMPLATE_FILE"
            git push origin HEAD:${{ github.event.pull_request.head.ref || github.ref_name }}
          else
            echo "✅ CODEOWNERS already up to date."
          fi
