name: Enforce Target Branch CODEOWNERS

on:
  pull_request:
    branches:
      - development
      - quality
      - main
      - hotfix

  push:
    branches:
      - development
      - quality
      - main

jobs:
  force-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Determine target branch
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi

      - name: Overwrite CODEOWNERS based on target branch
        run: |
          TARGET_BRANCH="${{ steps.vars.outputs.branch }}"
          echo "Detected target branch: $TARGET_BRANCH"

          if [[ "$TARGET_BRANCH" == "development" ]]; then
            echo "* @Ravikiran023" > .github/CODEOWNERS
            echo "Applied: * @Ravikiran023"

          elif [[ "$TARGET_BRANCH" == "quality" ]]; then
            echo "* @itsdarshan12" > .github/CODEOWNERS
            echo "Applied: * @itsdarshan12"

          elif [[ "$TARGET_BRANCH" == "main" ]]; then
            echo "* @treadstone26" > .github/CODEOWNERS
            echo "Applied: * @treadstone26"
          else
            echo "No enforcement rule for branch: $TARGET_BRANCH"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .github/CODEOWNERS
          git commit -m "ci: enforce CODEOWNERS for $TARGET_BRANCH" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.pull_request.head.ref || steps.vars.outputs.branch }} || echo "Push skipped on push event"
