name: Block CODEOWNERS Modifications

on:
  pull_request:
    branches:
      - development
      - quality
      - main
      - hotfix
  push:
    branches:
      - development
      - quality
      - main
      - hotfix

jobs:
  block-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect CODEOWNERS changes
        run: |
          if git diff --name-only origin/${{ github.event.pull_request.base.ref || github.ref_name }} | grep -q "^.github/CODEOWNERS$"; then
            echo "❌ CODEOWNERS file modification detected! This is not allowed."
            exit 1
          else
            echo "✅ No CODEOWNERS changes detected. Proceeding..."
          fi
