name: Validate CODEOWNERS

on:
  pull_request:
    branches:
      - development
      - quality
      - main
  push:
    branches:
      - development
      - quality
      - main

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate CODEOWNERS by target branch
        run: |
          BRANCH="${{ github.event.pull_request.base.ref || github.ref_name }}"
          echo "🔍 Validating CODEOWNERS for branch: $BRANCH"

          case "$BRANCH" in
            development)
              EXPECTED="@Ravikiran023"
              ;;
            quality)
              EXPECTED="@itsdarshan12"
              ;;
            main)
              EXPECTED="@treadstone26"
              ;;
            *)
              echo "✅ No enforcement for branch: $BRANCH"
              exit 0
              ;;
          esac

          # Extract actual owner from CODEOWNERS
          ACTUAL=$(grep -o '@.*' .github/CODEOWNERS | head -1)

          echo "Expected: $EXPECTED"
          echo "Actual:   $ACTUAL"

          if [[ "$EXPECTED" != "$ACTUAL" ]]; then
            echo "❌ CODEOWNERS mismatch. Expected: $EXPECTED but found: $ACTUAL"
            exit 1
          fi

          echo "✅ CODEOWNERS validated correctly for $BRANCH"
