name: Prevent CODEOWNERS Change

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  check-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Check for CODEOWNERS file change
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)
          echo "$CHANGED_FILES" | grep -q ".github/CODEOWNERS" && {
            echo "❌ You cannot modify .github/CODEOWNERS in this PR!";
            exit 1;
          } || echo "✅ CODEOWNERS file not modified."
